User.create(username: "Alex", password: "password")
User.create(username: "Guest", password: "password")
User.create(username: "Tom", password: "password")
User.create(username: "David", password: "password")
User.create(username: "Eileen", password: "password")

Snack.create(name: "Garlic Fries", picture_url: "http://farm3.static.flickr.com/2763/4069403884_519943cda5.jpg", description: "Super Duper", user_id: 1)
Snack.create(name: "Pizza", picture_url: "http://res.cloudinary.com/devwor0u0/image/upload/v1484623643/_0jpjeqtsyg-carissa-gan_jw7dcq.jpg", description: "Pizzetta", user_id: 1)
Snack.create(name: "Risotto", picture_url: "http://res.cloudinary.com/devwor0u0/image/upload/v1484623524/risotto_k66fea.jpg", description: "Don Pablo's", user_id: 1)
Snack.create(name: "Short Ribs", picture_url: "http://ot-foodspotting-production.s3.amazonaws.com/reviews/5725837/thumb_600.jpg?1454076792?1484869003", description: "Roka Akor", user_id: 1)
Snack.create(name: "Burrito", picture_url: "https://overeatingisunderrated.files.wordpress.com/2014/02/20140203-230037.jpg", description: "El Farlito", user_id: 2)
Snack.create(name: "Masala Dosa", picture_url: "https://static01.nyt.com/images/2015/01/28/dining/28KITCHEN1/28KITCHEN1-superJumbo.jpg", description: "Dosa", user_id: 2)
Snack.create(name: "Firecracker Beef", picture_url: "http://drakepost.com/wp-content/uploads/2010/12/osha-thai.jpg", description: "Osha", user_id: 2)
Snack.create(name: "Garlic Soy Wings", picture_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRKySBoqBQV2q2em2KBcNID1IhzQ8ebqLs2yPpyxsoIOPXLgGrFCg", description: "ZZAN", user_id: 2)
Snack.create(name: "SouthWest Burger", picture_url: "http://traffic411.com/wp-content/uploads/2012/10/umami_orig.jpg", description: "Umami Burger", user_id: 3)
Snack.create(name: "Chili Cheese Fries", picture_url: "http://media.longhornsteakhouse.com/en_us/images/product/d-chili-cheese-fries-dpv.jpg", description: "Longhorn", user_id: 3)
Snack.create(name: "Al Pastor Taco", picture_url: "http://cdn.funcheap.com/wp-content/uploads/2014/05/img_11701-550x366.jpg", description: "Don Pistos", user_id: 3)
Snack.create(name: "Ice Cream Sammy", picture_url: "http://www.sandiegomagazine.com/the-baked-bear.jpg", description: "The Baked Bear", user_id: 3)
Snack.create(name: "Frozen Yogurt", picture_url: "http://farm9.staticflickr.com/8108/8566847114_36a95b889a.jpg", description: "Pink Berry", user_id: 4)
Snack.create(name: "Chichen Korma", picture_url: "http://www.taste.com.au/images/recipes/agt/2011/06/chicken-korma-22295_l.jpeg", description: "India Palace", user_id: 4)
Snack.create(name: "Veggie Tempura", picture_url: "http://farm5.static.flickr.com/4098/4752532224_a3ecf47f5a.jpg", description: "Osha", user_id: 4)
Snack.create(name: "Roast Beef Sammy", picture_url: "http://www.berkeleyside.com/wp-content/uploads/2016/01/12362833_10156337885270416_2132211558409391242_o.jpg", description: "Ike's", user_id: 4)
Snack.create(name: "Kung Poa Pork", picture_url: "https://photos.smugmug.com/Portfolio/California-Gallery/i-8VBCsDH/0/L/san-francisco-ca-henrys-hunan-kung-pao-chicken-L.jpg", description: "Henry Hunan", user_id: 5)
Snack.create(name: "Shanghai Dumpling", picture_url: "http://www.yanksing.com/img/our-cuisine/deem-sum-gallery/specialty/shanghai_dmp_lrg.jpg", description: "Yank Sing", user_id: 5)
Snack.create(name: "Shrimp and Chive", picture_url: "http://ot-foodspotting-production.s3.amazonaws.com/reviews/2007526/thumb_600.jpg?1341522707", description: "Yank Sing", user_id: 5)
Snack.create(name: "Italian Sammy", picture_url: "http://ikeslairofredwoodcity.com/wp-content/uploads/background/73.jpg", description: "Ike's", user_id: 5)

Rating.create(user_id: 1, snack_id: 1, rating: 5)
Rating.create(user_id: 1, snack_id: 2, rating: 5)
Rating.create(user_id: 1, snack_id: 3, rating: 4)
Rating.create(user_id: 1, snack_id: 4, rating: 4)
Rating.create(user_id: 2, snack_id: 5, rating: 2)
Rating.create(user_id: 2, snack_id: 6, rating: 3)
Rating.create(user_id: 2, snack_id: 7, rating: 5)
Rating.create(user_id: 2, snack_id: 8, rating: 4)
Rating.create(user_id: 3, snack_id: 9, rating: 2)
Rating.create(user_id: 3, snack_id: 10, rating: 5)
Rating.create(user_id: 3, snack_id: 11, rating: 4)
Rating.create(user_id: 3, snack_id: 12, rating: 5)
Rating.create(user_id: 4, snack_id: 13, rating: 3)
Rating.create(user_id: 4, snack_id: 14, rating: 4)
Rating.create(user_id: 4, snack_id: 15, rating: 5)
Rating.create(user_id: 4, snack_id: 16, rating: 2)
Rating.create(user_id: 5, snack_id: 17, rating: 4)
Rating.create(user_id: 5, snack_id: 18, rating: 5)
Rating.create(user_id: 5, snack_id: 19, rating: 1)
Rating.create(user_id: 5, snack_id: 20, rating: 4)


Rating.create(user_id: 1, snack_id: 17, rating: 5)
Rating.create(user_id: 1, snack_id: 18, rating: 5)
Rating.create(user_id: 1, snack_id: 19, rating: 4)
Rating.create(user_id: 1, snack_id: 20, rating: 4)
Rating.create(user_id: 2, snack_id: 1, rating: 2)
Rating.create(user_id: 2, snack_id: 2, rating: 3)
Rating.create(user_id: 2, snack_id: 3, rating: 5)
Rating.create(user_id: 2, snack_id: 4, rating: 4)
Rating.create(user_id: 3, snack_id: 5, rating: 2)
Rating.create(user_id: 3, snack_id: 6, rating: 5)
Rating.create(user_id: 3, snack_id: 7, rating: 4)
Rating.create(user_id: 3, snack_id: 8, rating: 5)
Rating.create(user_id: 4, snack_id: 9, rating: 3)
Rating.create(user_id: 4, snack_id: 10, rating: 4)
Rating.create(user_id: 4, snack_id: 11, rating: 5)
Rating.create(user_id: 4, snack_id: 12, rating: 2)
Rating.create(user_id: 5, snack_id: 13, rating: 4)
Rating.create(user_id: 5, snack_id: 14, rating: 5)
Rating.create(user_id: 5, snack_id: 15, rating: 4)
Rating.create(user_id: 5, snack_id: 16, rating: 3)

Rating.create(user_id: 1, snack_id: 13, rating: 5)
Rating.create(user_id: 1, snack_id: 14, rating: 5)
Rating.create(user_id: 1, snack_id: 15, rating: 4)
Rating.create(user_id: 1, snack_id: 16, rating: 4)
Rating.create(user_id: 2, snack_id: 17, rating: 2)
Rating.create(user_id: 2, snack_id: 18, rating: 3)
Rating.create(user_id: 2, snack_id: 19, rating: 5)
Rating.create(user_id: 2, snack_id: 20, rating: 4)
Rating.create(user_id: 3, snack_id: 1, rating: 2)
Rating.create(user_id: 3, snack_id: 2, rating: 5)
Rating.create(user_id: 3, snack_id: 3, rating: 4)
Rating.create(user_id: 3, snack_id: 4, rating: 5)
Rating.create(user_id: 4, snack_id: 5, rating: 3)
Rating.create(user_id: 4, snack_id: 6, rating: 4)
Rating.create(user_id: 4, snack_id: 7, rating: 5)
Rating.create(user_id: 4, snack_id: 8, rating: 2)
Rating.create(user_id: 5, snack_id: 9, rating: 4)
Rating.create(user_id: 5, snack_id: 10, rating: 5)
Rating.create(user_id: 5, snack_id: 11, rating: 4)
Rating.create(user_id: 5, snack_id: 12, rating: 3)
